FROM node:25-alpine

USER root

RUN apk update && apk add --no-cache \
  git \
  nano \
  curl

WORKDIR /var/www/html

RUN git config --global --add safe.directory /var/www/html

EXPOSE 5173

CMD ["sh", "-c", "npm run dev:client"]
