import type { Migration } from "../../types/migrate.js";

export const migration: Migration = {
    name: "create_users",

    async up(query) {
        await query(`
            CREATE TABLE users (
                id UUID PRIMARY KEY DEFAULT uuidv7(),
                public_id INTEGER GENERATED BY DEFAULT AS IDENTITY,

                name VARCHAR(255) NOT NULL,
                email VARCHAR(255) UNIQUE,
                phone VARCHAR(30),
                profile_image TEXT,
                password TEXT NOT NULL,

                created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
                deleted_at TIMESTAMPTZ
            );

            CREATE INDEX idx_users_email ON users(email);
            CREATE INDEX idx_users_deleted_at ON users(deleted_at);
        `);
    },

    async down(query) {
        await query(`
            DROP TABLE IF EXISTS users;
        `);
    }
};