import type { Migration } from "../../types/migrate.js";

export const migration: Migration = {
    name: "create_user_store_access",

    async up(query) {
        await query(`
            CREATE TABLE user_store_access (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                store_id UUID NOT NULL REFERENCES stores(id) ON DELETE CASCADE,

                created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),

                CONSTRAINT user_store_access_user_id_store_id_unique UNIQUE (user_id, store_id)
            );

            CREATE INDEX idx_user_store_access_store_id
            ON user_store_access(store_id);
        `);
    },

    async down(query) {
        await query(`
            DROP TABLE IF EXISTS user_store_access;
        `);
    }
};
